# Generated by Django 4.2 on 2025-12-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FavoriteStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts_code", models.CharField(max_length=20)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("DEFAULT", "默认"),
                            ("WATCH", "观察"),
                            ("TOP", "龙头"),
                        ],
                        default="DEFAULT",
                        max_length=20,
                    ),
                ),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PatternFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern_id", models.CharField(max_length=50, verbose_name="形态ID")),
                ("pattern_type", models.CharField(default="PRESET", max_length=20)),
                ("add_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "形态收藏",
            },
        ),
        migrations.CreateModel(
            name="StockBasic",
            fields=[
                (
                    "ts_code",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="股票代码",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="股票名称")),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="所属行业"
                    ),
                ),
                (
                    "market_cap",
                    models.FloatField(
                        blank=True, null=True, verbose_name="总市值(亿元)"
                    ),
                ),
                (
                    "list_date",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="上市日期"
                    ),
                ),
                (
                    "is_dragon_tiger",
                    models.BooleanField(default=False, verbose_name="是否龙虎榜"),
                ),
            ],
            options={
                "verbose_name": "股票列表",
            },
        ),
        migrations.CreateModel(
            name="StockDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts_code", models.CharField(db_index=True, max_length=20)),
                ("trade_date", models.DateField(db_index=True)),
                ("open_price", models.FloatField()),
                ("close_price", models.FloatField()),
                ("high_price", models.FloatField()),
                ("low_price", models.FloatField()),
                ("vol", models.FloatField()),
                ("amount", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="SystemMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "related_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="TradeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts_code", models.CharField(max_length=20)),
                ("trade_date", models.DateField()),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "买入"), ("SELL", "卖出")], max_length=10
                    ),
                ),
                ("price", models.FloatField()),
                ("volume", models.IntegerField(default=100)),
                ("strategy_name", models.CharField(default="手动", max_length=50)),
                ("pnl", models.FloatField(blank=True, null=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="UserPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("DRAW", "趋势手绘"), ("KLINE", "K线构造")],
                        default="DRAW",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("data_points", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-create_time"],
            },
        ),
        migrations.AddIndex(
            model_name="stockdaily",
            index=models.Index(
                fields=["ts_code", "trade_date"], name="data_engine_ts_code_f6dfa1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockdaily",
            constraint=models.UniqueConstraint(
                fields=("ts_code", "trade_date"), name="unique_stock_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="patternfavorite",
            constraint=models.UniqueConstraint(
                fields=("pattern_id", "pattern_type"), name="unique_fav_pattern"
            ),
        ),
        migrations.AddConstraint(
            model_name="favoritestock",
            constraint=models.UniqueConstraint(
                fields=("ts_code",), name="unique_fav_stock"
            ),
        ),
    ]
