# Generated by Django 4.2 on 2025-12-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ts_code",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="股票代码"
                    ),
                ),
                (
                    "trade_date",
                    models.DateField(db_index=True, verbose_name="交易日期"),
                ),
                ("open", models.FloatField(verbose_name="开盘价")),
                ("high", models.FloatField(verbose_name="最高价")),
                ("low", models.FloatField(verbose_name="最低价")),
                ("close", models.FloatField(verbose_name="收盘价")),
                ("vol", models.FloatField(verbose_name="成交量(手)")),
                ("amount", models.FloatField(verbose_name="成交额(千元)")),
                (
                    "adj_factor",
                    models.FloatField(blank=True, null=True, verbose_name="复权因子"),
                ),
            ],
            options={
                "verbose_name": "日线行情",
                "verbose_name_plural": "日线行情",
            },
        ),
        migrations.CreateModel(
            name="TradeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts_code", models.CharField(max_length=20, verbose_name="股票代码")),
                ("trade_date", models.DateField(verbose_name="交易日期")),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "买入"), ("SELL", "卖出")],
                        max_length=10,
                        verbose_name="交易方向",
                    ),
                ),
                ("price", models.FloatField(verbose_name="成交均价")),
                ("volume", models.IntegerField(verbose_name="成交手数")),
                (
                    "strategy_name",
                    models.CharField(
                        default="DTW形态匹配", max_length=50, verbose_name="触发策略"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
            ],
            options={
                "verbose_name": "模拟交易记录",
                "verbose_name_plural": "模拟交易记录",
                "ordering": ["-create_time"],
            },
        ),
        migrations.AddIndex(
            model_name="stockdaily",
            index=models.Index(
                fields=["ts_code", "trade_date"], name="data_engine_ts_code_f6dfa1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockdaily",
            constraint=models.UniqueConstraint(
                fields=("ts_code", "trade_date"), name="unique_stock_date"
            ),
        ),
    ]
