# Generated by Django 4.2 on 2025-12-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="策略名称")),
                ("criteria", models.JSONField(default=dict, verbose_name="筛选条件")),
                (
                    "is_monitoring",
                    models.BooleanField(default=False, verbose_name="是否监控"),
                ),
                ("monitor_freq", models.IntegerField(default=60)),
                ("notify_msg", models.BooleanField(default=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-create_time"],
            },
        ),
        migrations.AlterModelOptions(
            name="patternfavorite",
            options={},
        ),
        migrations.AlterField(
            model_name="patternfavorite",
            name="pattern_id",
            field=models.CharField(max_length=50),
        ),
    ]
