# Generated by Django 4.2 on 2025-12-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_engine", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockdaily",
            old_name="close",
            new_name="close_price",
        ),
        migrations.RenameField(
            model_name="stockdaily",
            old_name="high",
            new_name="high_price",
        ),
        migrations.RenameField(
            model_name="stockdaily",
            old_name="low",
            new_name="low_price",
        ),
        migrations.RenameField(
            model_name="stockdaily",
            old_name="open",
            new_name="open_price",
        ),
        migrations.RemoveField(
            model_name="stockdaily",
            name="adj_factor",
        ),
    ]
