# Generated by Django 4.2 on 2025-12-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_engine", "0002_rename_close_stockdaily_close_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockBasic",
            fields=[
                (
                    "ts_code",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="股票代码",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="股票名称")),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="所属行业"
                    ),
                ),
                (
                    "market_cap",
                    models.FloatField(
                        blank=True, null=True, verbose_name="总市值(亿元)"
                    ),
                ),
                (
                    "list_date",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="上市日期"
                    ),
                ),
            ],
            options={
                "verbose_name": "股票列表",
                "verbose_name_plural": "股票列表",
            },
        ),
    ]
