# Generated by Django 4.2 on 2025-12-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_engine", "0002_userstrategy_alter_patternfavorite_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="traderecord",
            name="order_validity",
            field=models.CharField(default="day", max_length=20, verbose_name="有效期"),
        ),
        migrations.AddField(
            model_name="traderecord",
            name="trigger_condition",
            field=models.CharField(blank=True, max_length=100, verbose_name="触发条件"),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="pnl",
            field=models.FloatField(blank=True, null=True, verbose_name="盈亏"),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="strategy_name",
            field=models.CharField(default="手动交易", max_length=50),
        ),
    ]
