# Generated by Django 4.2 on 2025-12-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_engine", "0003_stockbasic"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts_code", models.CharField(max_length=20, verbose_name="股票代码")),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.CharField(blank=True, max_length=100, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "自选股",
            },
        ),
        migrations.CreateModel(
            name="UserPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="形态名称")),
                (
                    "type",
                    models.CharField(
                        choices=[("PRESET", "系统预设"), ("CUSTOM", "用户自定义")],
                        default="CUSTOM",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="形态含义(买入/卖出)"
                    ),
                ),
                ("data_points", models.TextField(verbose_name="数据点序列")),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "形态管理",
                "ordering": ["-create_time"],
            },
        ),
        migrations.AlterModelOptions(
            name="stockdaily",
            options={"verbose_name": "日线行情"},
        ),
        migrations.AlterModelOptions(
            name="traderecord",
            options={"ordering": ["-create_time"], "verbose_name": "交易记录"},
        ),
        migrations.AddField(
            model_name="traderecord",
            name="pnl",
            field=models.FloatField(blank=True, null=True, verbose_name="盈亏金额"),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="price",
            field=models.FloatField(verbose_name="成交单价"),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="strategy_name",
            field=models.CharField(
                default="手动交易", max_length=50, verbose_name="策略来源"
            ),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="volume",
            field=models.IntegerField(default=100, verbose_name="成交数量(股)"),
        ),
        migrations.AddConstraint(
            model_name="favoritestock",
            constraint=models.UniqueConstraint(
                fields=("ts_code",), name="unique_fav_stock"
            ),
        ),
    ]
