# Generated by Django 4.2 on 2025-12-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_engine", "0003_traderecord_order_validity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patternfavorite",
            options={"verbose_name": "形态收藏"},
        ),
        migrations.AlterModelOptions(
            name="userstrategy",
            options={"ordering": ["-create_time"], "verbose_name": "用户策略"},
        ),
        migrations.AddField(
            model_name="userstrategy",
            name="notify_email",
            field=models.BooleanField(default=False, verbose_name="邮件通知"),
        ),
        migrations.AlterField(
            model_name="patternfavorite",
            name="pattern_id",
            field=models.CharField(max_length=50, verbose_name="形态ID"),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="strategy_name",
            field=models.CharField(default="手动", max_length=50),
        ),
        migrations.AlterField(
            model_name="userstrategy",
            name="monitor_freq",
            field=models.IntegerField(default=60, verbose_name="监控频率(秒)"),
        ),
        migrations.AlterField(
            model_name="userstrategy",
            name="notify_msg",
            field=models.BooleanField(default=True, verbose_name="消息推送"),
        ),
    ]
