# Generated by Django 4.2 on 2025-12-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_engine",
            "0004_favoritestock_userpattern_alter_stockdaily_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "related_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="关联股票"
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-create_time"],
            },
        ),
        migrations.AlterModelOptions(
            name="favoritestock",
            options={},
        ),
        migrations.AlterModelOptions(
            name="stockbasic",
            options={"verbose_name": "股票列表"},
        ),
        migrations.AlterModelOptions(
            name="traderecord",
            options={"ordering": ["-create_time"]},
        ),
        migrations.AlterModelOptions(
            name="userpattern",
            options={"ordering": ["-create_time"]},
        ),
        migrations.RemoveField(
            model_name="userpattern",
            name="type",
        ),
        migrations.AddField(
            model_name="favoritestock",
            name="group",
            field=models.CharField(
                choices=[
                    ("DEFAULT", "默认分组"),
                    ("WATCH", "观察仓"),
                    ("TOP", "龙头股"),
                    ("HOLD", "持仓股"),
                ],
                default="DEFAULT",
                max_length=20,
                verbose_name="分组",
            ),
        ),
        migrations.AddField(
            model_name="stockbasic",
            name="is_dragon_tiger",
            field=models.BooleanField(default=False, verbose_name="是否龙虎榜"),
        ),
        migrations.AddField(
            model_name="userpattern",
            name="source_type",
            field=models.CharField(
                choices=[("DRAW", "鼠标手绘"), ("BUILD", "积木构造")],
                default="DRAW",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="pnl",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="strategy_name",
            field=models.CharField(default="手动交易", max_length=50),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="trade_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="trade_type",
            field=models.CharField(
                choices=[("BUY", "买入"), ("SELL", "卖出")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="ts_code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="volume",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="userpattern",
            name="data_points",
            field=models.TextField(verbose_name="数据序列"),
        ),
        migrations.AlterField(
            model_name="userpattern",
            name="description",
            field=models.CharField(blank=True, max_length=200, verbose_name="形态含义"),
        ),
    ]
