# Generated by Django 4.2 on 2025-12-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_engine", "0005_systemmessage_alter_favoritestock_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockbasic",
            name="is_dragon_tiger",
        ),
        migrations.AlterField(
            model_name="favoritestock",
            name="group",
            field=models.CharField(
                choices=[
                    ("DEFAULT", "默认分组"),
                    ("WATCH", "观察仓"),
                    ("TOP", "龙头股"),
                ],
                default="DEFAULT",
                max_length=20,
                verbose_name="分组",
            ),
        ),
        migrations.AlterField(
            model_name="systemmessage",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="systemmessage",
            name="related_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="systemmessage",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userpattern",
            name="source_type",
            field=models.CharField(
                choices=[("DRAW", "趋势手绘"), ("KLINE", "K线构造")],
                default="DRAW",
                max_length=10,
            ),
        ),
    ]
