# Generated by Django 4.2 on 2025-12-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_engine", "0006_remove_stockbasic_is_dragon_tiger_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatternFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern_id", models.CharField(max_length=50, verbose_name="形态ID")),
                ("pattern_type", models.CharField(default="PRESET", max_length=20)),
                ("add_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "形态收藏",
            },
        ),
        migrations.AlterModelOptions(
            name="stockdaily",
            options={},
        ),
        migrations.AddField(
            model_name="stockbasic",
            name="is_dragon_tiger",
            field=models.BooleanField(default=False, verbose_name="是否龙虎榜"),
        ),
        migrations.AlterField(
            model_name="favoritestock",
            name="group",
            field=models.CharField(
                choices=[("DEFAULT", "默认"), ("WATCH", "观察"), ("TOP", "龙头")],
                default="DEFAULT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="favoritestock",
            name="notes",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="favoritestock",
            name="ts_code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="stockdaily",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="stockdaily",
            name="close_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="stockdaily",
            name="high_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="stockdaily",
            name="low_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="stockdaily",
            name="open_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="stockdaily",
            name="trade_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="stockdaily",
            name="ts_code",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="stockdaily",
            name="vol",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="traderecord",
            name="strategy_name",
            field=models.CharField(default="手动", max_length=50),
        ),
        migrations.AlterField(
            model_name="userpattern",
            name="data_points",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="userpattern",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="userpattern",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="patternfavorite",
            constraint=models.UniqueConstraint(
                fields=("pattern_id", "pattern_type"), name="unique_fav_pattern"
            ),
        ),
    ]
